# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"


# Redirects
# https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
# https://docs.netlify.com/routing/redirects/redirect-options/
# https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

[[redirects]]
  from = "https://garrinada.org/*"
  to = "https://www.garrinada.cat/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://garrinada.netlify.app/*"
  to = "https://www.garrinada.cat/:splat"
  status = 301
  force = true
